# Site settings
title: carliflower.github.io
email: shadowform@gmail.io
description: > # this means to ignore newlines until "baseurl:"
  carliflower.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carliflower.github.io" # the base hostname & protocol for your site
github_username:  carliflower

# Build settings
markdown: kramdown
